export const citiesPeru = [
  'Amazonas',
  'Ancash',
  'Apurímac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Cusco',
  'Huancavelica',
  'Huánuco',
  'Ica',
  'Junín',
  'La Libertad',
  'Lambayeque',
  'Lima',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martín',
  'Tacna',
  'Tumbes',
  'Ucayali',
];

export const headerTable = [
  {
    text: 'ID',
    value: 'id',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Nombre de Catálogo',
    value: 'name',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Inversión Mínima',
    value: 'minimum_investment',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Monto de Separación',
    value: 'quota_price',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Fecha Pago Monto de Separación',
    value: 'quota_date',
    align: 'center',
    sortable: false,
  },
  {
    text: '% Primer Pago',
    value: 'first_payment',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Fecha Primer Pago',
    value: 'date_first_payment',
    align: 'center',
    sortable: false,
  },
  {
    text: '% Segundo Pago',
    value: 'second_payment',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Fecha Segundo Pago',
    value: 'date_second_payment',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Tipo de Moneda',
    value: 'coin',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Fecha de Llegada',
    value: 'arrivals',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Disponible',
    value: 'is_available',
    align: 'center',
    sortable: false,
  },
  { text: 'Acciones', value: 'actions', sortable: false, align: 'center' },
];
