export const headerUser = [
  {
    text: 'Nombre',
    value: 'name',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Email',
    value: 'email',
    align: 'center',
    sortable: false,
  },
  {
    text: 'DNI',
    value: 'dni',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Celular',
    value: 'phone',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Cuidad',
    value: 'city',
    align: 'center',
    sortable: false,
  },
  {
    text: 'Roles',
    value: 'roles',
    align: 'center',
    sortable: false,
  },
  { text: 'Acciones', value: 'actions', sortable: false, align: 'center' },
];
export const citiesPeru = [
  'Amazonas',
  'Ancash',
  'Apurímac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Cusco',
  'Huancavelica',
  'Huánuco',
  'Ica',
  'Junín',
  'La Libertad',
  'Lambayeque',
  'Lima',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martín',
  'Tacna',
  'Tumbes',
  'Ucayali',
];
